[agent]
  interval = "10s"
  hostname = "simple-bank-server"

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "system_metrics"

[[inputs.cpu]]
  percpu = true
  totalcpu = true

[[inputs.mem]]

[[inputs.system]]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"